apiVersion: apps/v1
kind: Deployment
metadata:
  name: gointerop-smart-on-fhir-cds
  labels:
    app: gointerop-smart-on-fhir-cds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gointerop-smart-on-fhir-cds    
  template:
    metadata:
      labels:
        app: gointerop-smart-on-fhir-cds
    spec:
      containers:
      - name: gointerop-smart-on-fhir-cds
        image: gointerop/smart-on-fhir-cds-service
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gointerop-smart-on-fhir-cds-service
spec:
  selector:
    app: gointerop-smart-on-fhir-cds
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gointerop-smart-on-fhir-cds-ingress
spec:
  rules:
  - http:
      paths:
      - path:
        backend:
          serviceName: gointerop-smart-on-fhir-cds-service
          servicePort: 8080